[package]
name = "atm-raytracer"
version = "0.1.0"
authors = ["Bartłomiej Kamiński <fizyk20@gmail.com>"]
edition = "2018"

[dependencies]
atm-refraction = "0.2"
dted = "0.1"
clap = "2.0"
image = { git = "https://github.com/fizyk20/image.git", branch = "rows" }
rayon = "1.0"
